name: Renovate
on:
  push:
    branches:
      - main
  # This lets you dispatch a renovate job with different cache options if you want to reset or disable the cache manually.
  workflow_dispatch:
  schedule:
    # Run every 30 minutes:
    - cron: '0,30 * * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: renovatebot/github-action@v40.1.3
        env:
          RENOVATE_REPOSITORIES: "demeyerthom/dependabot-monorepo-poc"
          RENOVATE_ONBOARDING: "false"
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}